
version: 0.2

env:
  variables:
    TF_VAR_environment: "dev"             # Override via CodeBuild env if needed
    TF_VAR_region: "ap-south-1"
  parameter-store:
    # Optionally store sensitive vars in SSM Parameter Store and map here
    # TF_VAR_bucket_name: "/iac/dev/bucket_name"

phases:
  install:
    commands:
      - echo "Installing Terraform ${TF_VER}"
      - curl -fsSL https://releases.hashicorp.com/terraform/${TF_VER}/terraform_${TF_VER}_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip && mv terraform /usr/local/bin/ && rm terraform.zip
      - terraform -version
  pre_build:
    commands:
      - cd terraform-iac-poc
      - terraform fmt -check
      - terraform init -backend-config=backend.hcl
      - terraform validate
  build:
    commands:
      - terraform plan -var-file=envs/dev/terraform.tfvars -out=tfplan.bin
  post_build:
    commands:
      # For POC we auto-apply; in prod split plan/apply or require manual approval
      - terraform apply -auto-approve tfplan.bin

artifacts:
  files:
    - "**/*"
